config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'search#index'
  resources :search
  resources :videos
  resources :genres
  resources :films
  root 'films#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/film.rb
class Film < ApplicationRecord
  belongs_to  :genre
  accepts_nested_attributes_for :genre

  mount_uploader :image, ImageUploader

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many  :films
end

app/models/video.rb
class Video < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy]

  # GET /films
  # GET /films.json
  def index
    @films = Film.all
  end

  # GET /films/1
  # GET /films/1.json
  def show
    @videos = Video.where(:film_id => @film.id)
  end

  # GET /films/new
  def new
    @film = Film.new
    @film.build_genre
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Film was successfully created.' }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: 'Film was successfully updated.' }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to films_url, notice: 'Film was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def film_params
      params.require(:film).permit(:titre, :realisateur, :date_sortie, :date_production, :synopsis, :pays, :genre_id, :duree, :image)
    end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genre_params
      params.require(:genre).permit(:nom)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @variable = 4
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    if params.has_key?(:genre)
      @genre = Genre.find(params[:genre]).nom
      @films = Film.where(genre_id: params[:genre])
      @films.inspect
    else
      @genre = "Pas de genre spécifié"
    end
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:lien, :film_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/film_helper.rb
module FilmHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/video_helper.rb
module VideoHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/films/_form.html.erb
<%= form_for(film, :html => {:mutlipart => true}) do |f| %>
  <% if film.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
      <% film.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titre %>
    <%= f.text_field :titre, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :realisateur %>
    <%= f.text_field :realisateur, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :date_sortie %>
    <%= f.date_select :date_sortie %>
  </div>

  <div class="field">
    <%= f.label :date_production %>
    <%= f.date_select :date_production %>
  </div>


    <div class="field">
      <label for="genre_id">Genre</label>
      <%= f.collection_select :genre_id, Genre.all, :id, :nom, {}, {:class=>'btn btn-default'} %>
    </div>

  <div class="field">
    <%= f.label :synopsis %>
    <%= f.text_area :synopsis, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :pays %>
    <%= f.text_field :pays, class: 'form-control' %>
  </div>


  <div class="field">
    <%= f.label :duree %>
    <%= f.text_field :duree, class: 'form-control' %>
  </div>


    <div class="field">
      <%= f.label :image %>
      <%= f.file_field :image, class: 'form-control' %>
    </div>

  <div class="actions">
    <%= f.submit 'Create', :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/films/edit.html.erb
<h1>Editing Film</h1>

<%= render 'form', film: @film %>

<%= link_to 'Show', @film %> |
<%= link_to 'Back', films_path %>

app/views/films/index.html.erb
<div class="films">
<p id="notice"><%= notice %></p>

<h1 class="page-title">Films</h1>

  <div class="container-films list-films">
    <% @films.each do |film| %>
        <div class="film item">

          <div class="image">
            <%= image_tag film.image %>
          </div>

          <div class="infos">
            <div class="titre"><%= link_to film.titre, film %><%=  %></div>
            <span class="genre"><%= Genre.find(film.genre_id).nom %></span>
            <span class="date"><%= film.date_sortie.strftime("%Y") %></span>
          </div>

          <div class="actions text-right">
            <%= link_to 'Edit', edit_film_path(film), class:'btn btn-primary' %>
            <%= link_to 'Destroy', film, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
    <% end %>
  </div>


</div>

app/views/films/new.html.erb
<h1>New Film</h1>

<%= render 'form', film: @film %>

<%= link_to 'Back', films_path %>

app/views/films/show.html.erb
<p id="notice"><%= notice %></p>

    <div class="image-container">
      <div class="image"><%= image_tag @film.image %></div>
      <div class="actions">
        <%= link_to 'Edit', edit_film_path(@film),class:'btn btn-primary' %> |
        <%= link_to 'Back', films_path , class:'btn btn-default'%>
      </div>
    </div>
    <div class="info-container text-center">
      <p class="titreFilmDescription">
        <strong><%= @film.titre %></strong>

      </p>

      <div class="leftSideFilmDescription">
      <p>
        <strong>Realisateur:</strong>
        <%= @film.realisateur %>
      </p>
      <p>
        <strong>Date sortie:</strong>
        <%= @film.date_sortie %>
      </p>
      <p>
        <strong>Date production:</strong>
        <%= @film.date_production %>
      </p>
      </div>

      <div class="rightSideFilmDescription">
      <p>
        <strong>Genre:</strong>
        <%= Genre.find(@film.genre_id).nom %>
      </p>
      <p>
        <strong>Pays:</strong>
        <%= @film.pays %>
      </p>
      <p>
        <strong>Duree:</strong>
        <%= @film.duree %>
      </p>
      </div>

      <p class="text-left">
        <strong>Synopsis:</strong>
        <%= @film.synopsis %>
      </p>

      <p class="bandeAnnonce">
        <%= @videos.each do |video| %>
            <iframe src="<%= video.lien %>" frameborder="0" allowfullscreen></iframe>
        <% end %>
      </p>
</div>

app/views/genres/_form.html.erb
<%= form_for(genre) do |f| %>
  <% if genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
      <% genre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %>
    <%= f.text_field :nom, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit 'Create', :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<h1>Editing Genre</h1>

<%= render 'form', genre: @genre %>

<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>

app/views/genres/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Genres</h1>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td><%= genre.nom %></td>
        <td><%= link_to 'Show', genre %></td>
        <td><%= link_to 'Edit', edit_genre_path(genre) %></td>
        <td><%= link_to 'Destroy', genre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Genre', new_genre_path %>

app/views/genres/new.html.erb
<h1>New Genre</h1>

<%= render 'form', genre: @genre %>

<%= link_to 'Back', genres_path %>

app/views/genres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @genre.nom %>
</p>

<%= link_to 'Edit', edit_genre_path(@genre) %> |
<%= link_to 'Back', genres_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>

<p>Test variable <%= @variable %></p>

app/views/layouts/_footer.html.erb
<footer class="container-fluid text-center">
    <p>&copy; - Sloth Company</p>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="logo" href="/"><%= image_tag "SlothIcon.png" %> </a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home</a></li>
        <li><%= link_to 'Ajouter un film', new_film_path %></li>
        <li><%= link_to 'Ajouter une video', new_video_path %></li>
        <li><%= link_to 'Ajouter un genre', new_genre_path %></li>
      </ul>
      <form class="navbar-form navbar-right" action="/search">
        <div class="form-group input-group">
          <select name="genre" id="genre-search" class="btn btn-default">
            <% Genre.all.each do |genre| %>
            <option value="<%= genre.id %>"><%= genre.nom %></option>
            <% end %>
          </select>

          <span class="input-group-btn">
            <button class="btn btn-default" type="submit">
              <span class="glyphicon glyphicon-search"></span>
            </button>
          </span>
        </div>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StreamSloth</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/header" %>
  <div class="container-fluid text-center">
    <div class="col-sm-8 text-left">
      <%= yield %>
    </div>
  </div>
  <%= render "layouts/footer" %>
  </body>
</html>

app/views/search/index.html.erb
<div class="films">
  <p id="notice"><%= notice %></p>

  <h1 class="page-title">Films pour le genre "<%= @genre %>"</h1>

  <div class="container-films list-films">
    <% @films.each do |film| %>
        <div class="film item">

          <div class="image">
            <%= image_tag film.image %>
          </div>

          <div class="infos">
            <div class="titre"><%= link_to film.titre, film %><%=  %></div>
            <span class="genre"><%= Genre.find(film.genre_id).nom %></span>
            <span class="date"><%= film.date_sortie.strftime("%Y") %></span>
          </div>

          <div class="actions text-right">
            <%= link_to 'Edit', edit_film_path(film), class:'btn btn-primary' %>
            <%= link_to 'Destroy', film, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
    <% end %>
  </div>

  <br>

  <%= link_to 'New Film', new_film_path %>

</div>

app/views/videos/_form.html.erb
<%= form_for(video) do |f| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lien %>
    <%= f.text_field :lien %>
  </div>

    <div class="field">
      <label for="film_id">Film</label>
    <%= f.collection_select :film_id, Film.all, :id, :titre, {}, {:class=>'btn btn-default'} %>
    </div>

  <div class="actions">
    <%= f.submit 'Create', :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Videos</h1>

<table>
  <thead>
    <tr>
      <th>Lien</th>
      <th>Film</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.lien %></td>
        <td><%= video.film_id %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lien:</strong>
  <iframe src="<%= @video.lien %>" frameborder="0" allowfullscreen></iframe>
</p>

<p>
  <strong>Film:</strong>
  <%= @video.film_id %>
</p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>